#############################################################
#                                                           #
# Copyright (c) 2022, University of California, Los Angeles #
#                                                           #
# Authors: Kenny J. Chen, Brett T. Lopez                    #
# Contact: kennyjchen@ucla.edu, btlopez@ucla.edu            #
#                                                           #
#############################################################

dlo:

  odomNode:

    initialPose:
      use: false
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0

    preprocessing:
      cropBoxFilter:
        use: true
        size: 1.0
      voxelFilter:
        scan:
          use: true
          res: 0.25
        submap:
          use: true
          res: 0.5

    keyframe:
      threshD: 5.0    # 关键帧距离, 越小数量越多
      threshR: 45.0   # 关键帧角度差

    submap:
      keyframe:   # 这几个是获取submap的最小距离,越大越好
        knn: 10
        kcv: 10
        kcc: 10

    imu:
      calibTime: 3
      bufferSize: 2000

    gicp:
      minNumPoints: 10
      s2s:
        kCorrespondences: 10    # 这个不记得了
        maxCorrespondenceDistance: 1.0  # 这个参数是近邻关系的最大阈值, 超过就忽略
        maxIterations: 32               # 越大越好
        transformationEpsilon: 0.01     # 收敛系数 越小越好
        euclideanFitnessEpsilon: 0.01   # 和上面那个差不多
        ransac:           # 剔除噪点的
          iterations: 5
          outlierRejectionThresh: 1.0
      s2m:                              # 同上
        kCorrespondences: 20
        maxCorrespondenceDistance: 0.5
        maxIterations: 32                                         
        transformationEpsilon: 0.01
        euclideanFitnessEpsilon: 0.01
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
